# -*- coding: utf-8 -*-
"""ch2-20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3A2yYHi0j_UPMWFr4GoS9y-jAZCzU6i
"""

from datetime import datetime
from time import sleep

def log1(message, when=datetime.now()):
  print('%s: %s' % (when, message))

log1('Hi there!')
sleep(0.1)
log1('Hi again!')

def log2(message, when=None):
  """
    Log a message with a timestamp.
    
    Args:
        mesage: mesage to print
        when : datetime of when...
  """
  when = datetime.now() if when is None else when
  print('%s: %s' % (when, message))

log2('Hi there!')
sleep(0.1)
log2('Hi again!')

import json
def decode1(data, default={}):
  try:
    return json.loads(data)
  except ValueError:
    return default

foo = decode1('bad data')
foo['stuff'] = 5
bar = decode1('also bad')
bar['meep'] = 1
print('Foo', foo)
print('Bar', bar)

def decode2(data, default=None):
  if default is None:
    default = {}
  try:
    return json.loads(data)
  except ValueError:
    return default

foo = decode2('bad data')
foo['stuff'] = 5
bar = decode2('also bad')
bar['meep'] = 1
print('Foo', foo)
print('Bar', bar)

