# -*- coding: utf-8 -*-
"""stock_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1101LqguTLu_An2yQmcXSnokiG-4oXwry
"""

import pandas as pd
import pandas_datareader as pdr

stock_type = {
    'kospi': 'stockMkt',
    'kosdaq': 'kosdaqMkt'
}

def get_code(df, name):
  code = df.query("name=='{}'".format(name))['code'].to_string(index=False)
  code = code.strip()
  return code

def get_download_stock(market_type=None):
  market_type_param = stock_type[market_type]
  download_link = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&marketType=' + market_type_param

  df = pd.read_html(download_link, header=0)[0]
  return df;

def get_download_kospi():
  df = get_download_stock('kospi')
  df.종목코드 = df.종목코드.map('{:06d}.KS'.format)
  return df

def get_download_kosdaq():
  df = get_download_stock('kosdaq')
  df.종목코드 = df.종목코드.map('{:06d}.KQ'.format)
  return df

# kospi, kosdaq 종목코드 각각 다운로드
kospi_df = get_download_kospi()
kosdaq_df = get_download_kosdaq()

# data frame merge
code_df = pd.concat([kospi_df, kosdaq_df])

# data frame정리
code_df = code_df[['회사명', '종목코드']]

# data frame title 변경 '회사명' = name, 종목코드 = 'code'
code_df = code_df.rename(columns={'회사명': 'name', '종목코드': 'code'})


code = get_code(code_df, '카카오')

df = pdr.get_data_yahoo(code)

df['Close'].plot()


